// ignore_for_file: constant_identifier_names

class AnalyticsConstant {
  static const String ANALYTICS_SPLASH_SCREEN = "SPLASH_SCREEN";
  static const String ANALYTICS_HOME_SCREEN = "HOME_SCREEN";

  static const String ANALYTICS_SIGN_UP_EMAIL_SCREEN = "SIGN_UP_EMAIL_SCREEN";
  static const String ANALYTICS_SIGN_UP_DETAILS_SCREEN =
      "SIGN_UP_DETAILS_SCREEN";
  static const String ANALYTICS_SIGN_UP_SUCCESS_SCREEN =
      "SIGN_UP_SUCCESS_SCREEN";
  static const String ANALYTICS_LOGIN_SCREEN = "LOGIN_SCREEN";
  static const String ANALYTICS_FORGOT_PASSWORD_SCREEN =
      "FORGOT_PASSWORD_SCREEN";
  static const String ANALYTICS_FORGOT_PASSWORD_SUCCESS_SCREEN =
      "FORGOT_PASSWORD_SUCCESS_SCREEN";

  static const String ANALYTICS_ACCOUNT_INFO_SCREEN = 'ACCOUNT_INFO_SCREEN';
  static const String ANALYTICS_EDIT_ACCOUNT_SCREEN = "EDIT_ACCOUNT_SCREEN";

  static const String ANALYTICS_ABOUT_US_SCREEN = 'ABOUT_US_SCREEN';

  static const String ANALYTICS_CRANE_LOCATION_SCREEN = 'CRANE_LOCATION_SCREEN';
  static const String ANALYTICS_LOTO_LIST_SCREEN = "LOTO_LIST_SCREEN";
  static const String ANALYTICS_LOTO_MAP_SCREEN = "LOTO_MAP_SCREEN";
  static const String ANALYTICS_LOTO_PANEL_DETAIL_SCREEN =
      "LOTO_PANEL_DETAIL_SCREEN";

  static const String ANALYTICS_CHEMICAL_REGISTER_CATEGORY_LIST_SCREEN =
      "CHEMICAL_REGISTER_CATEGORY_LIST_SCREEN";
  static const String ANALYTICS_CHEMICAL_REGISTER_SUBCATEGORY_LIST_SCREEN =
      "CHEMICAL_REGISTER_SUBCATEGORY_LIST_SCREEN";
  static const String ANALYTICS_CHEMICAL_DETAIL_SCREEN =
      "CHEMICAL_DETAIL_SCREEN";
  static const String ANALYTICS_SDS_SUMMARY_SCREEN = "SDS_SUMMARY_SCREEN";

  static const String ANALYTICS_PDF_VIEW_SCREEN = 'PDF_VIEW_SCREEN';
  static const String ANALYTICS_GALLERY_VIEW_SCREEN = 'GALLERY_VIEW_SCREEN';
}
